Release building updates

diff --git a/build/make-release b/build/make-release
--- a/build/make-release
+++ b/build/make-release
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-PATH="${PATH}:/sbin:/usr/sbin:/usr/local/sbin"
+PATH="${HOME}/root/cross-compilers:${PATH}:/sbin:/usr/sbin:/usr/local/sbin"
 export PATH
 
 VERSION="$1"
@@ -10,7 +10,7 @@ if [ -z "${VERSION}" ]; then
 	exit 1
 fi
 
-for dir in ../../archive/ ../archive/; do
+for dir in ../../archive/ ../archive/ ..; do
 	CACKEY_TARBALL="$(readlink -f "${dir}/cackey-${VERSION}.tar.gz")"
 
 	if [ -f "${CACKEY_TARBALL}" ]; then
@@ -18,20 +18,36 @@ for dir in ../../archive/ ../archive/; do
 	fi
 done
 
+if [ ! -f "${CACKEY_TARBALL}" ]; then
+	echo "Tarball not found" >&2
+
+	exit 1
+fi
+
 # Create RPM, SRPM, and Slackware package
 ## Create RPM/SRPM
-mkdir -p ~/rpmbuild/SPECS ~/rpmbuild/SOURCES
+(
+	eval "$(setup-cc x86_64-redhat5-linux)"
 
-cp "${CACKEY_TARBALL}" ~/rpmbuild/SOURCES/ || exit 1
-tar -xOf "${CACKEY_TARBALL}" cackey-${VERSION}/cackey.spec > ~/rpmbuild/SPECS/cackey-${VERSION}.spec || exit 1
+	mkdir -p ~/rpmbuild/SPECS ~/rpmbuild/SOURCES
 
-rpmbuild -ba ~/rpmbuild/SPECS/cackey-${VERSION}.spec || exit 1
+	cp "${CACKEY_TARBALL}" ~/rpmbuild/SOURCES/ || exit 1
+	tar -xOf "${CACKEY_TARBALL}" cackey-${VERSION}/cackey.spec > ~/rpmbuild/SPECS/cackey-${VERSION}.spec || exit 1
+
+	rpmbuild --target x86_64-redhat5-linux -ba ~/rpmbuild/SPECS/cackey-${VERSION}.spec || exit 1
+)
+
+(
+	eval "$(setup-cc x86_64-redhat5-linux 32)"
+	rpmbuild --target i386-redhat5-linux -ba ~/rpmbuild/SPECS/cackey-${VERSION}.spec || exit 1
+)
 
 # Create Debian package from RPM
 mkdir -p ~/rpmbuild/DEB
 "$(dirname "$0")/rpm2deb" ~/rpmbuild/RPMS/i386/cackey-${VERSION}-1.i386.rpm ~/rpmbuild/DEB/cackey_${VERSION}-1_i386.deb
+"$(dirname "$0")/rpm2deb" ~/rpmbuild/RPMS/x86_64/cackey-${VERSION}-1.x86_64.rpm ~/rpmbuild/DEB/cackey_${VERSION}-1_amd64.deb
 
-## Create Slackware package
+# Create Slackware package
 mkdir -p ~/rpmbuild/TGZ
 
 WORKDIR="${TMPDIR:-/tmp}/cackey-build-$$${RANDOM}${RANDOM}${RANDOM}"
@@ -45,7 +61,23 @@ tar -xf "${CACKEY_TARBALL}"
 
 cd "cackey-${VERSION}" || exit 1
 
-./configure --prefix=/usr
+case "$(uname -m)" in
+	x86_64)
+		ARCH=x86_64
+		LIBDIR=/usr/lib64
+		;;
+	i?86)
+		ARCH=i486
+		LIBDIR=/usr/lib
+		;;
+	*)
+		echo "Unknown ARCH" >&2
+
+		exit 1
+		;;
+esac
+
+./configure --prefix=/usr --libdir=${LIBDIR}
 make
 make install DESTDIR="${WORKDIRINSTROOT}"
 
@@ -68,10 +100,10 @@ pcsc-lite
 __EOF__
 
 cd "${WORKDIRINSTROOT}" || exit 1
-makepkg -l y -c n "${WORKDIR}/cackey-${VERSION}-i486-1.tgz"
-gzip -dc "${WORKDIR}/cackey-${VERSION}-i486-1.tgz" | tardy -User root -Group root | gzip -9 > "${WORKDIR}/cackey-${VERSION}-i486-1.tgz.new"
-mv "${WORKDIR}/cackey-${VERSION}-i486-1.tgz.new" "${WORKDIR}/cackey-${VERSION}-i486-1.tgz"
-cp "${WORKDIR}/cackey-${VERSION}-i486-1.tgz" ~/rpmbuild/TGZ
+makepkg -l y -c n "${WORKDIR}/cackey-${VERSION}-${ARCH}-1.tgz"
+gzip -dc "${WORKDIR}/cackey-${VERSION}-${ARCH}-1.tgz" | tardy -User root -Group root | gzip -9 > "${WORKDIR}/cackey-${VERSION}-${ARCH}-1.tgz.new"
+mv "${WORKDIR}/cackey-${VERSION}-${ARCH}-1.tgz.new" "${WORKDIR}/cackey-${VERSION}-${ARCH}-1.tgz"
+cp "${WORKDIR}/cackey-${VERSION}-${ARCH}-1.tgz" ~/rpmbuild/TGZ
 
 # Cleanup
 rm -rf "${WORKDIR}"
